[package]
name = "logseq-python"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
keywords.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
name = "logseq"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
logseq = { path = "../../" }
pyo3 = { workspace = true }
